/**
 * The places a schema can be imported from. Each source knows which importer to run, which SQL dialect
 * to expect, and how to get the schema out of that system (the instructions shown in the Import dialog).
 */
import { IMPORT_FORMATS, ImportFormat, ImportResult, detectFormat, importText } from "./index";
import { SQL_DIALECTS, SqlDialect } from "../sql/dialects";

export type InstructionBlock =
  | { kind: "text"; text: string }
  /** `shell` puts a "$" prompt in front (terminal command); placeholders are written as <name>. */
  | { kind: "code"; code: string; shell?: boolean };

export interface ImportSource {
  id: string;
  label: string;
  group: "auto" | "database" | "file" | "data";
  /** Which importer runs. "auto" detects the format from the text. */
  format: ImportFormat;
  /** SQL dialect the parser should expect (database sources only). */
  dialect?: SqlDialect;
  /** Heading of the instructions pane. */
  title: string;
  blocks: InstructionBlock[];
  /** `accept` attribute of the file picker. */
  accept: string;
  placeholder: string;
}

const t = (text: string): InstructionBlock => ({ kind: "text", text });
const sh = (code: string): InstructionBlock => ({ kind: "code", code, shell: true });
const sql = (code: string): InstructionBlock => ({ kind: "code", code });

const PASTE = "Open the file, copy its content and paste it into the box on the right — or use Upload file.";
const SQL_ACCEPT = ".sql,.ddl,.txt";

export const IMPORT_SOURCES: ImportSource[] = [
  {
    id: "auto",
    label: "Auto-detect",
    group: "auto",
    format: "auto",
    title: "Auto-detect",
    blocks: [
      t("Paste anything — DesignDB works out what it is: SQL (and which database dialect), DBML, Prisma, Django models, Rails schema, Mermaid or JSON."),
      t("Not sure how to get your schema out of your database? Pick your database from the list at the top left for step-by-step instructions."),
    ],
    accept: `${SQL_ACCEPT},.dbml,.prisma,.py,.rb,.json,.mmd,.mermaid,.db,.sqlite,.sqlite3`,
    placeholder: "-- Paste SQL, DBML, Prisma, Django, Rails, Mermaid or JSON here…\n-- …or drag & drop a file onto this box",
  },

  // ───────────── databases ─────────────
  {
    id: "mysql",
    label: "MySQL / MariaDB",
    group: "database",
    format: "sql",
    dialect: "mysql",
    title: "MySQL",
    blocks: [
      t("1. Install mysqldump. It comes with the MySQL / MariaDB client tools."),
      t("2. In your terminal run the following command (structure only, no data). On Linux you might need to add sudo before it."),
      sh("mysqldump -h <host> -u <username> -P <port> -p --no-data --skip-comments <database_name> > <output_path>"),
      t("Example"),
      sh("mysqldump -h localhost -u root -P 3306 -p --no-data --skip-comments ecommerce > schema.sql"),
      t(`3. ${PASTE}`),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the output of mysqldump here…",
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    group: "database",
    format: "sql",
    dialect: "postgres",
    title: "PostgreSQL",
    blocks: [
      t("1. Install pg_dump. It comes with the PostgreSQL client tools."),
      t("2. In your terminal run the following command (schema only, no data). On Linux you might need to add sudo before it."),
      sh("pg_dump -h <host> -p <port> -U <username> -d <database_name> --schema-only --no-owner --no-privileges -f <output_path>"),
      t("Example"),
      sh("pg_dump -h localhost -p 5432 -U postgres -d ecommerce --schema-only --no-owner --no-privileges -f schema.sql"),
      t("Add -n <schema_name> to export a single schema."),
      t(`3. ${PASTE}`),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the output of pg_dump here…",
  },
  {
    id: "mssql",
    label: "SQL Server",
    group: "database",
    format: "sql",
    dialect: "mssql",
    title: "SQL Server",
    blocks: [
      t("Option A — SQL Server Management Studio (SSMS)"),
      t("1. Right-click your database → Tasks → Generate Scripts…"),
      t("2. Choose “Script entire database and all database objects”, then open Advanced and set “Types of data to script” to “Schema only”."),
      t("3. Save the script to a file, then open it and copy its content into the box on the right — or use Upload file."),
      t("Option B — command line with mssql-scripter (schema only is its default)"),
      sh("mssql-scripter -S <server> -d <database_name> -U <username> > <output_path>"),
      t("Example"),
      sh("mssql-scripter -S localhost -d ecommerce -U sa > schema.sql"),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the script generated by SSMS or mssql-scripter here…",
  },
  {
    id: "oracle",
    label: "Oracle",
    group: "database",
    format: "sql",
    dialect: "oracle",
    title: "Oracle",
    blocks: [
      t("1. Open SQL Developer or SQL*Plus, connected as a user that can read the schema."),
      t("2. Run these queries. The first returns the tables, the second the foreign keys. Copy both results."),
      sql(
        "SET LONG 1000000 PAGESIZE 0 LINESIZE 32767\n\nSELECT DBMS_METADATA.GET_DDL('TABLE', table_name, owner)\nFROM all_tables WHERE owner = '<SCHEMA_NAME>';\n\nSELECT DBMS_METADATA.GET_DDL('REF_CONSTRAINT', constraint_name, owner)\nFROM all_constraints WHERE constraint_type = 'R' AND owner = '<SCHEMA_NAME>';"
      ),
      t("Example — for the schema HR, replace <SCHEMA_NAME> with HR."),
      t(`3. Paste the copied DDL into the box on the right.`),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the DDL returned by DBMS_METADATA.GET_DDL here…",
  },
  {
    id: "sqlite",
    label: "SQLite",
    group: "database",
    format: "sql",
    dialect: "sqlite",
    title: "SQLite",
    blocks: [
      t("Easiest: use Upload file and pick your .db / .sqlite file. It is read in your browser — nothing is uploaded — and opens in the reverse-engineering tool."),
      t("Or export the structure as text with the sqlite3 command-line tool:"),
      sh("sqlite3 <database_file> .schema > <output_path>"),
      t("Example"),
      sh("sqlite3 ecommerce.db .schema > schema.sql"),
      t(`Then ${PASTE.charAt(0).toLowerCase()}${PASTE.slice(1)}`),
    ],
    accept: `${SQL_ACCEPT},.db,.sqlite,.sqlite3`,
    placeholder: "-- Paste the output of “.schema” here (or upload a .db / .sqlite file)…",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    group: "database",
    format: "sql",
    dialect: "snowflake",
    title: "Snowflake",
    blocks: [
      t("1. Open a worksheet in Snowsight (or SnowSQL)."),
      t("2. Run the query below and copy the single result cell."),
      sql("SELECT GET_DDL('SCHEMA', '<database_name>.<schema_name>', TRUE);"),
      t("Example"),
      sql("SELECT GET_DDL('SCHEMA', 'ANALYTICS.PUBLIC', TRUE);"),
      t("3. Paste the copied DDL into the box on the right."),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the result of GET_DDL here…",
  },
  {
    id: "bigquery",
    label: "Google BigQuery",
    group: "database",
    format: "sql",
    dialect: "bigquery",
    title: "Google BigQuery",
    blocks: [
      t("1. Open the BigQuery console and start a new query."),
      t("2. Run the query below. Copy the value of the result cell."),
      sql("SELECT STRING_AGG(ddl, ';\\n') FROM `<project>.<dataset>`.INFORMATION_SCHEMA.TABLES\nWHERE table_type = 'BASE TABLE';"),
      t("Example"),
      sql("SELECT STRING_AGG(ddl, ';\\n') FROM `my-project.ecommerce`.INFORMATION_SCHEMA.TABLES\nWHERE table_type = 'BASE TABLE';"),
      t("3. Paste the copied DDL into the box on the right."),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the CREATE TABLE statements from INFORMATION_SCHEMA here…",
  },
  {
    id: "redshift",
    label: "Amazon Redshift",
    group: "database",
    format: "sql",
    dialect: "redshift",
    title: "Amazon Redshift",
    blocks: [
      t("1. Install the admin.v_generate_tbl_ddl view from AWS's amazon-redshift-utils (one time)."),
      t("2. Run this query in your SQL client and copy the ddl column."),
      sql("SELECT ddl FROM admin.v_generate_tbl_ddl\nWHERE schemaname = '<schema_name>'\nORDER BY tablename, seq;"),
      t("Example"),
      sql("SELECT ddl FROM admin.v_generate_tbl_ddl\nWHERE schemaname = 'public'\nORDER BY tablename, seq;"),
      t("No admin views? Run SHOW TABLE <schema_name>.<table_name>; for each table instead."),
      t("3. Paste the copied DDL into the box on the right."),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the CREATE TABLE statements here…",
  },
  {
    id: "databricks",
    label: "Databricks",
    group: "database",
    format: "sql",
    dialect: "databricks",
    title: "Databricks",
    blocks: [
      t("1. Open a SQL editor or notebook attached to your workspace."),
      t("2. Run this for each table you want to import and copy the results."),
      sql("SHOW CREATE TABLE <catalog>.<schema>.<table_name>;"),
      t("Example"),
      sql("SHOW CREATE TABLE main.ecommerce.orders;"),
      t("Foreign keys defined as ALTER TABLE … ADD CONSTRAINT statements are picked up as relationships."),
      t("3. Paste all the statements into the box on the right."),
    ],
    accept: SQL_ACCEPT,
    placeholder: "-- Paste the SHOW CREATE TABLE output here…",
  },

  // ───────────── schema files ─────────────
  {
    id: "dbml",
    label: "DBML",
    group: "file",
    format: "dbml",
    title: "DBML",
    blocks: [
      t("Paste DBML (Database Markup Language) — for example copied from dbdiagram.io or produced by dbml-cli."),
      t("Table, Ref, Enum, TableGroup, Note, Project, indexes, DiagramView, Dep and Records blocks are all understood."),
      t("Example"),
      sql("Table users {\n  id integer [pk, increment]\n  email varchar [unique, not null]\n}\n\nTable posts {\n  id integer [pk]\n  user_id integer [ref: > users.id]\n}"),
    ],
    accept: ".dbml,.txt",
    placeholder: "// Paste DBML here…",
  },
  {
    id: "prisma",
    label: "Prisma",
    group: "file",
    format: "prisma",
    title: "Prisma",
    blocks: [
      t("1. Open your schema.prisma (usually prisma/schema.prisma) and copy all of it."),
      t("Starting from an existing database? Let Prisma write the file for you first:"),
      sh("npx prisma db pull"),
      t("2. Paste it into the box on the right. Models, enums, @id / @@id, @unique, @@index, @default, @map, relations with onDelete / onUpdate and implicit many-to-many are imported."),
    ],
    accept: ".prisma,.txt",
    placeholder: "// Paste your schema.prisma here…",
  },
  {
    id: "django",
    label: "Django",
    group: "file",
    format: "django",
    title: "Django models",
    blocks: [
      t("1. Open your app's models.py and copy the model classes."),
      t("Starting from an existing database? Let Django write the models for you first:"),
      sh("python manage.py inspectdb > models.py"),
      t("2. Paste them into the box on the right. ForeignKey, OneToOneField and ManyToManyField become relationships."),
    ],
    accept: ".py,.txt",
    placeholder: "# Paste your Django models.py here…",
  },
  {
    id: "rails",
    label: "Rails",
    group: "file",
    format: "rails",
    title: "Rails schema",
    blocks: [
      t("1. Generate or open db/schema.rb:"),
      sh("rails db:schema:dump"),
      t("2. Copy its content and paste it into the box on the right. create_table blocks and add_foreign_key lines are imported."),
    ],
    accept: ".rb,.txt",
    placeholder: "# Paste your db/schema.rb here…",
  },
  {
    id: "mermaid",
    label: "Mermaid",
    group: "file",
    format: "mermaid",
    title: "Mermaid ER diagram",
    blocks: [
      t("Paste an erDiagram block. Relationship cardinalities decide which table holds the foreign key; missing key columns are added for you."),
      t("Example"),
      sql("erDiagram\n  USERS ||--o{ POSTS : writes\n  USERS {\n    int id PK\n    string email\n  }\n  POSTS {\n    int id PK\n    string title\n  }"),
    ],
    accept: ".mmd,.mermaid,.txt",
    placeholder: "erDiagram\n  …",
  },
  {
    id: "json",
    label: "JSON",
    group: "file",
    format: "json",
    title: "JSON",
    blocks: [
      t("Paste a DesignDB model (Export → JSON) or the { entities, relationships } shape used by AI schema generators."),
      t("Example"),
      sql('{\n  "entities": [\n    { "name": "users", "attributes": [{ "name": "id", "dataType": "integer", "isPrimaryKey": true }] }\n  ],\n  "relationships": []\n}'),
    ],
    accept: ".json,.txt",
    placeholder: "{ … }",
  },

  // ───────────── data files ─────────────
  {
    id: "csv",
    label: "CSV",
    group: "data",
    format: "csv",
    title: "CSV",
    blocks: [
      t("Upload one or more .csv or .tsv files — or drop them here. Each file becomes a table named after the file (comma, semicolon, tab and pipe separators are all recognised)."),
      t("The first row must hold the column names. Column types are worked out from the values: integer, decimal, boolean, date, timestamp, time, UUID, JSON or text."),
      t("A column called id becomes the primary key. Columns like customer_id become relationships to the customers table when you import both files together."),
      t("The first 100 rows are kept as the table's sample data, so the SQL playground, the sample-data editor and the exports can use them."),
      t("Pasting instead? Put a line -- table: <name> above each CSV."),
      t("Example"),
      sql("-- table: customers\nid,email,full_name\n1,alice@example.com,Alice Smith\n2,bob@example.com,Bob Johnson\n\n-- table: orders\nid,customer_id,total,placed_at\n10,1,59.90,2024-03-01 10:15:00\n11,2,12.50,2024-03-02 16:40:00"),
    ],
    accept: ".csv,.tsv,.txt",
    placeholder: "-- table: customers\nid,email,full_name\n1,alice@example.com,Alice Smith\n…\n\n-- …or drop one or more .csv files onto this box",
  },
];

export function getImportSource(id: string | undefined): ImportSource {
  return IMPORT_SOURCES.find((s) => s.id === id) || IMPORT_SOURCES[0];
}

/** The source that matches an auto-detected format (used when a dropped file is not what the source expected). */
export function sourceForFormat(format: ImportFormat): ImportSource {
  if (format === "sql" || format === "auto") return IMPORT_SOURCES[0];
  return IMPORT_SOURCES.find((s) => s.id === format) || IMPORT_SOURCES[0];
}

export interface ImportAnalysis {
  empty: boolean;
  result: ImportResult | null;
  /** What the text looks like, regardless of the selected source. */
  detected: Exclude<ImportFormat, "auto"> | null;
  /** Human label of what will be imported, e.g. "PostgreSQL" or "Prisma schema". */
  label: string;
  /** The chosen source failed while the text looks like a different format. */
  mismatch: boolean;
}

/** Runs the importer for the selected source and summarises the outcome (used for the live summary line). */
export function analyzeImport(text: string, source: ImportSource, filename?: string): ImportAnalysis {
  if (!text.trim()) return { empty: true, result: null, detected: null, label: "", mismatch: false };
  const detected = detectFormat(text, filename);
  const format: ImportFormat = source.format === "auto" ? detected : source.format;
  const result = importText(text, format, { filename, dialect: source.dialect });
  const failed = result.errors.length > 0;
  const mismatch = source.format !== "auto" && detected !== source.format && failed;
  let label: string;
  if (result.format === "sql") label = SQL_DIALECTS.find((d) => d.id === (result.dialect ?? source.dialect))?.label || "SQL";
  else label = IMPORT_FORMATS.find((f) => f.id === result.format)?.label || result.format;
  return { empty: false, result, detected, label, mismatch };
}
